# Auto-generated replay script
import argparse
import sys
import bpy
from infinigen.core.util import blender as butil


def parse_args(argv=None):
    if argv is None:
        argv = sys.argv
    if '--' in argv:
        argv = argv[argv.index('--') + 1:]
    else:
        argv = []
    parser = argparse.ArgumentParser(description='Replay logged asset')
    parser.add_argument('--output-blend', default=WindowsPath('D:/OneDrive/Infinigen/_out/asset_logging/variant_042/ChairFactory_042_replay.blend'), help='Path to save the replayed .blend file')
    parser.add_argument('--skip-save', action='store_true', help='Do not save a .blend file after replay')
    return parser.parse_args(argv)

def run(args):
    butil.clear_scene()
    bpy.ops.mesh.primitive_cube_add(location=[0, 0, 0])
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['Cube']"), True)
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['Cube']"))
    bpy.ops.curve.primitive_bezier_curve_add(location=[0, 0, 0])
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.subdivide(number_cuts=4)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=31)
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=63)
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=25)
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=40)
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=3)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.convert(target='MESH')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(WELD, **{'merge_threshold': 0.001})")
    modify_mesh(resolve("bpy.data.objects['BézierCurve']"), 'WELD', merge_threshold=0.001)
    bpy.ops.object.modifier_apply(modifier='modify_mesh(MIRROR, **{})')
    modify_mesh(resolve("bpy.data.objects['BézierCurve']"), 'MIRROR')
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.fill_grid(use_interp_simple=True)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(SOLIDIFY, **{'thickness': 0.0692797576724562, 'offs")
    modify_mesh(resolve("bpy.data.objects['BézierCurve']"), 'SOLIDIFY', thickness=0.0692797576724562, offset=0)
    bpy.ops.object.modifier_apply(modifier="modify_mesh(SUBSURF, **{'levels': 1, 'render_levels': 1, 'subdi")
    modify_mesh(resolve("bpy.data.objects['BézierCurve']"), 'SUBSURF', levels=1, render_levels=1, subdivision_type='SIMPLE')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(BEVEL, **{'width': 0.0346398788362281, 'segments': ")
    modify_mesh(resolve("bpy.data.objects['BézierCurve']"), 'BEVEL', width=0.0346398788362281, segments=8)
    bpy.ops.curve.primitive_bezier_curve_add(location=[0, 0, 0])
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=64)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.convert(target='MESH')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(WELD, **{'merge_threshold': 0.001})")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.001']"), 'WELD', merge_threshold=0.001)
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.001']"), True)
    bpy.ops.curve.primitive_bezier_curve_add(location=[0, 0, 0])
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=64)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.convert(target='MESH')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(WELD, **{'merge_threshold': 0.001})")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.002']"), 'WELD', merge_threshold=0.001)
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.002']"), True)
    bpy.ops.curve.primitive_bezier_curve_add(location=[0, 0, 0])
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=64)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.convert(target='MESH')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(WELD, **{'merge_threshold': 0.001})")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.003']"), 'WELD', merge_threshold=0.001)
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.003']"), True)
    bpy.ops.curve.primitive_bezier_curve_add(location=[0, 0, 0])
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=64)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.convert(target='MESH')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(WELD, **{'merge_threshold': 0.001})")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.004']"), 'WELD', merge_threshold=0.001)
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.004']"), True)
    bpy.ops.curve.primitive_bezier_curve_add(location=[0, 0, 0])
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=64)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.convert(target='MESH')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(WELD, **{'merge_threshold': 0.001})")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.005']"), 'WELD', merge_threshold=0.001)
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.005']"), True)
    bpy.ops.curve.primitive_bezier_curve_add(location=[0, 0, 0])
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=64)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.convert(target='MESH')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(WELD, **{'merge_threshold': 0.001})")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.006']"), 'WELD', merge_threshold=0.001)
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.006']"), True)
    bpy.ops.curve.primitive_bezier_curve_add(location=[0, 0, 0])
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=61)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.convert(target='MESH')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(WELD, **{'merge_threshold': 0.001})")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.007']"), 'WELD', merge_threshold=0.001)
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_edges_move(TRANSFORM_OT_translate={'value': [0.0, 0.056648852816008434, 0.0]})
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_region_move(TRANSFORM_OT_translate={'value': [0.0, 0.0, 0.056648852816008434]})
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.007']"), True)
    bpy.ops.object.modifier_apply(modifier="modify_mesh(BEVEL, **{'width': 0.0346398788362281, 'segments': ")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.007']"), 'BEVEL', width=0.0346398788362281, segments=8)
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.curve.primitive_bezier_curve_add(location=[0, 0, 0])
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=64)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.convert(target='MESH')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(WELD, **{'merge_threshold': 0.001})")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.008']"), 'WELD', merge_threshold=0.001)
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_edges_move(TRANSFORM_OT_translate={'value': [0.0, 0.056648852816008434, 0.0]})
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_region_move(TRANSFORM_OT_translate={'value': [0.0, 0.0, 0.056648852816008434]})
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.008']"), True)
    bpy.ops.object.modifier_apply(modifier="modify_mesh(BEVEL, **{'width': 0.0346398788362281, 'segments': ")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.008']"), 'BEVEL', width=0.0346398788362281, segments=8)
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.curve.primitive_bezier_curve_add(location=[0, 0, 0])
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=64)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.convert(target='MESH')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(WELD, **{'merge_threshold': 0.001})")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.009']"), 'WELD', merge_threshold=0.001)
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_edges_move(TRANSFORM_OT_translate={'value': [0.056648852816008434, 0.0, 0.0]})
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_region_move(TRANSFORM_OT_translate={'value': [0.0, 0.0, 0.056648852816008434]})
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.009']"), True)
    bpy.ops.object.modifier_apply(modifier="modify_mesh(BEVEL, **{'width': 0.0346398788362281, 'segments': ")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.009']"), 'BEVEL', width=0.0346398788362281, segments=8)
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.curve.primitive_bezier_curve_add(location=[0, 0, 0])
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=64)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.convert(target='MESH')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(WELD, **{'merge_threshold': 0.001})")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.010']"), 'WELD', merge_threshold=0.001)
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_edges_move(TRANSFORM_OT_translate={'value': [0.056648852816008434, 0.0, 0.0]})
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_region_move(TRANSFORM_OT_translate={'value': [0.0, 0.0, 0.056648852816008434]})
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.010']"), True)
    bpy.ops.object.modifier_apply(modifier="modify_mesh(BEVEL, **{'width': 0.0346398788362281, 'segments': ")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.010']"), 'BEVEL', width=0.0346398788362281, segments=8)
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.curve.primitive_bezier_curve_add(location=[0, 0, 0])
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.subdivide(number_cuts=1)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=39)
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=60)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.convert(target='MESH')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(WELD, **{'merge_threshold': 0.001})")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.011']"), 'WELD', merge_threshold=0.001)
    bpy.ops.object.modifier_apply(modifier='geo_radius')
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.curve.primitive_bezier_curve_add(location=[0, 0, 0])
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.subdivide(number_cuts=1)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=39)
    bpy.ops.curve.select_all(action='DESELECT')
    bpy.ops.curve.subdivide(number_cuts=60)
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.convert(target='MESH')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(WELD, **{'merge_threshold': 0.001})")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.012']"), 'WELD', merge_threshold=0.001)
    bpy.ops.object.modifier_apply(modifier='geo_radius')
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.object.join()
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_mode(type='EDGE')
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_mode(type='EDGE')
    bpy.ops.mesh.select_all(action='DESELECT')
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.bridge_edge_loops(number_cuts=64, interpolation='LINEAR', smoothness=0.39415735492420423, profile_shape_factor=0.3127194261577573)
    bpy.ops.mesh.select_loose()
    bpy.ops.mesh.delete()
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.modifier_apply(modifier="modify_mesh(SOLIDIFY, **{'thickness': 0.04450499251969543, 'off")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.013']"), 'SOLIDIFY', thickness=0.04450499251969543, offset=0)
    bpy.ops.object.modifier_apply(modifier="modify_mesh(BEVEL, **{'width': 0.0346398788362281, 'segments': ")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.013']"), 'BEVEL', width=0.0346398788362281, segments=8)
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_edges_move(TRANSFORM_OT_translate={'value': [0.056648852816008434, 0.0, 0.0]})
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_region_move(TRANSFORM_OT_translate={'value': [0.0, 0.056648852816008434, 0.0]})
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.001']"), True)
    bpy.ops.object.modifier_apply(modifier="modify_mesh(BEVEL, **{'width': 0.0346398788362281, 'segments': ")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.001']"), 'BEVEL', width=0.0346398788362281, segments=8)
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_edges_move(TRANSFORM_OT_translate={'value': [0.056648852816008434, 0.0, 0.0]})
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_region_move(TRANSFORM_OT_translate={'value': [0.0, 0.056648852816008434, 0.0]})
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.002']"), True)
    bpy.ops.object.modifier_apply(modifier="modify_mesh(BEVEL, **{'width': 0.0346398788362281, 'segments': ")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.002']"), 'BEVEL', width=0.0346398788362281, segments=8)
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_edges_move(TRANSFORM_OT_translate={'value': [0.056648852816008434, 0.0, 0.0]})
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_region_move(TRANSFORM_OT_translate={'value': [0.0, 0.056648852816008434, 0.0]})
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.003']"), True)
    bpy.ops.object.modifier_apply(modifier="modify_mesh(BEVEL, **{'width': 0.0346398788362281, 'segments': ")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.003']"), 'BEVEL', width=0.0346398788362281, segments=8)
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_edges_move(TRANSFORM_OT_translate={'value': [0.056648852816008434, 0.0, 0.0]})
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_region_move(TRANSFORM_OT_translate={'value': [0.0, 0.056648852816008434, 0.0]})
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.004']"), True)
    bpy.ops.object.modifier_apply(modifier="modify_mesh(BEVEL, **{'width': 0.0346398788362281, 'segments': ")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.004']"), 'BEVEL', width=0.0346398788362281, segments=8)
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_edges_move(TRANSFORM_OT_translate={'value': [0.04450499251969543, 0.0, 0.0]})
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_region_move(TRANSFORM_OT_translate={'value': [0.0, 0.04450499251969543, 0.0]})
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.005']"), True)
    bpy.ops.object.modifier_apply(modifier="modify_mesh(BEVEL, **{'width': 0.0346398788362281, 'segments': ")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.005']"), 'BEVEL', width=0.0346398788362281, segments=8)
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_edges_move(TRANSFORM_OT_translate={'value': [0.04450499251969543, 0.0, 0.0]})
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.extrude_region_move(TRANSFORM_OT_translate={'value': [0.0, 0.04450499251969543, 0.0]})
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve.006']"), True)
    bpy.ops.object.modifier_apply(modifier="modify_mesh(BEVEL, **{'width': 0.0346398788362281, 'segments': ")
    modify_mesh(resolve("bpy.data.objects['BézierCurve.006']"), 'BEVEL', width=0.0346398788362281, segments=8)
    bpy.ops.object.modifier_apply(modifier='geo_attribute')
    bpy.ops.object.join()
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
    apply_transform(resolve("bpy.data.objects['BézierCurve']"))
    bpy.ops.object.material_slot_add()
    bpy.ops.object.material_slot_add()
    bpy.ops.object.parent_no_inverse_set(keep_transform=False)
    bpy.ops.file.autopack_toggle()
    bpy.ops.wm.save_as_mainfile(filepath='_out\\asset_logging\\variant_042\\ChairFactory_042.blend')
    bpy.ops.file.autopack_toggle()
    save_blend("WindowsPath('_out/asset_logging/variant_042/ChairFactory_042.blend')", autopack=True)

if __name__ == '__main__':
    _args = parse_args()
    run(_args)
    if not _args.skip_save:
        bpy.ops.wm.save_as_mainfile(filepath=_args.output_blend)
